### ISSUE TITLE
How to install grapher

### ISSUE THREAD

**Issue by ilayshp** [elayabharath/Dynamo-Addons#1]
Hello
Thank you for utilities! I compile this toolkit.
How  to install grapher?

**Comment by elayabharath** [comment]
Hi @ilayshp, I have published a package with the graph functionality just now, you can get it from Dynamo package manager under 'Grapher'.

There are  some limitations with the library - the pie chart and histogram plots will produce SVG files in your desktop on every change - I will fix that soon. Otherwise for gauge and scatter plot, you can view the results from the watch image node.

Let me know if this works for you.

**Comment by ilayshp** [comment]
Hello. Thank you!
Most things work!
Also looking forward for curve output for svgPort!
